baseurl = "https://alex.rbind.io"
title = "Alex"
languagecode = "en-us"
theme = "hugo-black-and-light-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Alex"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Posts"
    url  = "/"

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]
  taxonomy = [ "HTML", "RSS" ]
  taxonomyTerm = [ "HTML", "RSS" ]